name: Update Subscriptions

on:
  schedule:
    - cron: "0 */3 * * *"  # 每 3 小时自动更新
  workflow_dispatch:        # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      # 4️⃣ 拉取订阅
      - name: Fetch subscriptions
        run: python fetch_subscriptions.py

      # 5️⃣ 挑选香港节点
      - name: Pick HK nodes
        run: python pick_hk_nodes.py

      # 6️⃣ 二阶段测速 & 优选
      - name: Speedtest & Select Best Nodes
        run: python speed_test.py
        continue-on-error: false  # 测速失败整个流程报错，保证结果有效

      # 7️⃣ 提交并推送生成的订阅
      - name: Commit and Push best_nodes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add best_nodes.yaml best_nodes.json
          git commit -m "Update best_nodes $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
